### ISSUE TITLE
Remove mutation cache

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/dashboards#123]
After #54.

Remove the mutation cache and use the new computer readable format of mutations and insertions directly.

**Comment by chaoran-chen** [comment]
Could you please expand a bit more on why the cache should be removed?

At the moment, one of the core motivations for the mutation cache (and the date cache) is to have only a single object instance per mutation which makes mutations easily comparable (just with `===`) and allows us to use mutation objects as keys in a `Map` or have a `Set` of mutations.

**Comment by fengelniederhammer** [comment]
As discussed: We delete the cache for now. We can bring it back later, if we know that we need it.
