### ISSUE TITLE
Components: Develop error handling

### ISSUE THREAD

**Issue by JonasKellerer** [GenSpectrum/dashboards#143]
Develop a method to provide the user with error information. Most of the time error occur when LAPIS is not reachable. This can already happen in the `gs-app` component fetching the reference genome.

More tbd

**Comment by fengelniederhammer** [comment]
Let's start thinking about how we want to implement this. Then we can implement it soon.

**Comment by fengelniederhammer** [comment]
Maybe we can simply use `useErrorBoundary` in all Preact based components?
https://preactjs.com/guide/v10/hooks

**Comment by fengelniederhammer** [comment]
Related: #75
