### ISSUE TITLE
Mutation filter: question mark

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/dashboards#157]
Show a question mark that provide additional information about the mutation filter syntax

**Comment by fengelniederhammer** [comment]
See https://github.com/GenSpectrum/dashboards/pull/149#discussion_r1568656962. As discussed:
* Show the `?` button that we also have for the diagram. The button should show information on how to use the mutations filter field.
* Maybe also give examples of valid input in the placeholder text.
