### ISSUE TITLE
Add clades for H5N1

### ISSUE THREAD

**Issue by anna-parker** [GenSpectrum/dashboards#179]
We can add clade labels using
1.  [LABEL](https://wonder.cdc.gov/amd/flu/label/) built by the CDC to assign avian flu clades

2. [nextclade H5Nx dataset](https://github.com/nextstrain/nextclade_data/blob/master/data/community/moncla-lab/iav-h5/ha/2.3.2.1/README.md) is available here (it includes the 2014 clade split: see https://onlinelibrary.wiley.com/doi/full/10.1111/irv.12324, seems to be the last official WHO clade assignment), it was shown to be close to the CDC tool LABEL and we already use nextclade for other clades so it should be easy to add.

**Comment by fengelniederhammer** [comment]
Has to wait until #35 is finished. We need a clade input field, which is being rebuilt there.
