### ISSUE TITLE
Storybook PR previews

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/dashboards#223]
Would it be easy to create preview deployments for the components again? We have a Vercal Pro Plan (thanks to their open-source support program).

**Comment by fengelniederhammer** [comment]
I think it should be relatively simple to set it up.
https://vercel.com/guides/storybook-with-vercel

**Comment by JonasKellerer** [comment]
It is setup and all PRs and pushes of branches will be deployed. 

The main deployment is here: [dashboards-components.vercel.app](https://dashboards-components.vercel.app/)
