### ISSUE TITLE
Develop a small Astro example

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/dashboards#232]

**Comment by chaoran-chen** [comment]
I experimented a bit and it works quite well already. Two major blockers that I experienced are #245 and #250.

The code is in https://github.com/GenSpectrum/astro-dashboard-playground

<details>
<summary>Screenshot</summary>

![image](https://github.com/GenSpectrum/dashboards/assets/18666552/4711f55d-8aa7-4b94-9c3f-bc6109f53eee)
</details>
