### ISSUE TITLE
Show pathogen-specific last-updated date in footer

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/dashboards#233]
At the moment, we show in the footer "Data last updated on: TODO". Instead, it should show the last update date using the data version from LAPIS. This should be pathogen-/LAPIS instance-specific. On pages that don't show actual data (e.g., the landing page), it shouldn't show a date at all.

**Comment by JonasKellerer** [comment]
Related: #234, #225

**Comment by fengelniederhammer** [comment]
Take the timestamp from the LAPIS data version and parse it back to a date to show something like on Cov Spectrum: 

![Image](https://github.com/user-attachments/assets/61ef8758-5008-4ec4-8fcb-541ba77c78ea)
