### ISSUE TITLE
Make tab header bar mobile friendly

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/dashboards#234]
Currently the tab header bar is too large (horizontally) for mobile views. Maybe `“overflow: scroll;` is already enough, because scrolling horizontally on mobile devices is rather simple.

**Comment by chaoran-chen** [comment]
This is a bit more difficult than I imagined: adding `overflow-x: scroll;` to the whole toolbar element breaks the popover-dialogs in the toolbar such as the proportion dialog:

![image](https://github.com/GenSpectrum/dashboards/assets/18666552/06d5671d-62f1-4395-b259-a66ea517d287)

I'm not sure how to best solve this. Can we improve the way the popover is implemented?

Generally, I really like the horizontal scrolling solution as opposite to introducing a dropdown or context menu which would require additional clicks.

**Comment by JonasKellerer** [comment]
I also run into the same problem, but with the info button. I'll look into this.

**Comment by JonasKellerer** [comment]
As discussed: we now use `flex-wrap` to wrap the toolbar below the tab selection.
