### ISSUE TITLE
For all paginated tables: make number entries per table configurable

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/dashboards#271]
For all paginated tables, at the moment, if the maintainer sets a height that doesn't exactly fit 10 entries, we have either too much whitespace or we have to scroll to see the pagination bar:

<img width="612" alt="image" src="https://github.com/GenSpectrum/dashboards/assets/18666552/c4e0d01b-4a87-4254-abcc-e35d9c78218e">

It would be great if the maintainer can define how many entries a page should have.

This applies to all paginated tables: the aggregate table component, the data tables in the different visualization components and the mutation grid.

**Comment by JonasKellerer** [comment]
As discussed, we tackle this issue in two ways. In a first step, we let the maintainers set the number of elements per page. They are then responsible that the height of the container matches the height of the provided number of entries per page. 
In a second step we try to evaluate the number of entries from the height of the parent component.
