### ISSUE TITLE
Show total number of sequences

### ISSUE THREAD

**Issue by chaoran-chen** [GenSpectrum/dashboards#336]
For all the views that we currently have, it would be nice to show the total number of filtered sequences. At the moment, we only see the number of sequences stratified by time / location / etc. but can't see the total number.

(Question: are there other useful metrics to show?)

**Comment by JonasKellerer** [comment]
Part of this ticket is to create a proposed design for a metric component. The design could include a metric container component, which bundles the other components together.

Metric ideas:
- number of sequences
- overall proportion
- relative growth advantage

**Comment by JonasKellerer** [comment]
Waiting on https://github.com/GenSpectrum/dashboard-components/issues/549
