### ISSUE TITLE
Submit button for search requires 2 actions instead of 1 to submit - this is confusing

### ISSUE THREAD

**Issue by anna-parker** [GenSpectrum/dashboards#35]
When I am searching for sequencing I keep forgetting that I need to enter and then still click submit to search - normally this is one action. It is especially annoying as if I forget to enter before pressing submit, then the page reloads and resets my filters (e.g. in the percentage of mutations) and I have to start from the beginning in my search for variants of interest:
<img width="315" alt="image" src="https://github.com/user-attachments/assets/84f86026-0521-417b-a432-ca1fad23cf63">

**Comment by JonasKellerer** [comment]
Waiting for #473
