### ISSUE TITLE
Mutations in search field not synced with URL and subsequent search operations.

### ISSUE THREAD

**Issue by anna-parker** [GenSpectrum/dashboards#36]
When I add a mutation e.g.. 
<img width="315" alt="image" src="https://github.com/user-attachments/assets/fea76707-e9c5-4a8d-be91-1d117e8f2853">
it is added to the URL. However, when I remove it using the x - it is not removed from the URL: 
<img width="737" alt="image" src="https://github.com/user-attachments/assets/c266ffa0-9394-4631-b076-78a6e052c4fb">
This means when the page is reloaded (e.g. if I add another filter) the mutation filter is still there. This means I have to always manually edit the URL to remove mutations or press the return button (if I am lucky and haven't done too complicated searches beforehand). 

But when I go back the filter will be cleared from the URL BUT the mutation filter will show up again: 
<img width="500" alt="image" src="https://github.com/user-attachments/assets/c0f51c74-0937-4555-8d3f-d6a517cef99a">

**Comment by fengelniederhammer** [comment]
Maybe #35 and https://github.com/GenSpectrum/dashboard-components/issues/481 and https://github.com/GenSpectrum/dashboard-components/issues/482 already fix this - let's block for now and reevaluate when those tickets are done.

**Comment by fengelniederhammer** [comment]
The relevant blockers are merged - let's check whether we think that this is sufficienetly solved.

**Comment by JonasKellerer** [comment]
I looked at it again. Still the behavior is there, what Anya describes: When one is on a page with mutation (also in the url), and then clicks on the 'x' button, the url is not changed. One has to click on the submit button. This is currently the expected behavior. Therefore, I will close this ticket.
