### ISSUE TITLE
Comparison to baseline - Prevalence over time is broken on staging

### ISSUE THREAD

**Issue by anna-parker** [GenSpectrum/dashboards#421]
![image](https://github.com/user-attachments/assets/51ba4af3-a19a-42c3-88ef-aa723d8b23b9)

error reads: Unexpected value '[]' for "numeratorFilters": Array must contain at least 1 element(s)

**Comment by fengelniederhammer** [comment]
It works when you add a variant - the fix should be that we add another text here that says "select a variant on the left" instead of the diagram if none is selected.
