### ISSUE TITLE
Location filter: Properly handle error when fetching autocomplete data

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/dashboards#75]
Currently, it looks like this when the LAPIS call fails:

![grafik](https://github.com/GenSpectrum/dashboards/assets/92720311/c8c9f739-7cc9-4577-ac72-66fb2e86131e)

What should we display instead?

**Comment by JonasKellerer** [comment]
If the maintainer inserts wrong filters, then the message should include the lapis error.

Also we wait for building a dashboard and then see, what would be necessary.
