### ISSUE TITLE
Notification backend: add authentication

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/dashboards#75]
Integrate the backend with the GitHub login. For now only check that the user is logged in.

**Comment by JonasKellerer** [comment]
As discussed: we no longer want to do this. Auth.js seems to be incompatible with spring boot security (without custom solutions). We now secure the backend, by not exposing it to the internet. The backend will be accessed directly from the astro backend which does not need authentication, or via proxy endpoints from client side. These proxy endpoints can then be secured by auth.js.
