### ISSUE TITLE
Notification backend: add authorization

### ISSUE THREAD

**Issue by fengelniederhammer** [GenSpectrum/dashboards#76]
Connect subscriptions with the respective user that created the subscription. A user should only be able to query their own subscriptions.

Create a separate user table that stores a uuid that serves as primary key to identify the user in the backend.

**Comment by JonasKellerer** [comment]
This worked in testing for #75. Maybe it helps here:

```
@GetMapping("/subscriptions", produces = [MediaType.APPLICATION_JSON_VALUE])
    @Operation(
        summary = "Get all subscriptions of a user",
        description = "Returns a list of all subscriptions of a user.",
    )
    fun getSubscriptions(@AuthenticationPrincipal oauth2User: OAuth2User): List<Subscription> {

        log.info { "Getting subscriptions for user id $oauth2User.name" }
        log.info { "More info on user: ${oauth2User.attributes}" }

        return subscriptionModel.getSubscriptions()
    }
 ```

**Comment by JonasKellerer** [comment]
As discussed: We no longer want to do authentication for the backend. Thus, we only have to provide the backend with user information for authorization.

The backend should take a user id as a request parameter and use this for authorization.
